const CACHE_NAME="veiculo-familiar-v2"
const URLS=[
"./",
"./index.html",
"./manifest.json",
"./css/style.css",
"./js/config.js",
"./js/app.js",
"./js/veiculos.js",
"./js/motoristas.js",
"./js/abastecimentos.js",
"./js/camera.js",
"./js/alertas.js",
"./js/relatorios.js"
]
self.addEventListener("install",event=>{
event.waitUntil(
caches.open(CACHE_NAME).then(cache=>cache.addAll(URLS))
)
self.skipWaiting()
})
self.addEventListener("activate",event=>{
event.waitUntil(
caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE_NAME).map(key=>caches.delete(key))))
)
self.clients.claim()
})
self.addEventListener("fetch",event=>{
event.respondWith(
caches.match(event.request).then(response=>response||fetch(event.request))
)
})
